version: '3.9'
services:
  api:
    container_name: okra-payment-api
    image: okra-payment-api:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start
    ports:
      - 8000:8000
    networks:
      - server-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    environment:
      MONGO_URI: ${MONGO_URI}
      SERVER_PORT: ${SERVER_PORT}
networks:
  server-network: